# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oierlauzi/git/zuazo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oierlauzi/git/zuazo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oierlauzi/git/zuazo/CMakeFiles /home/oierlauzi/git/zuazo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oierlauzi/git/zuazo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zuazo

# Build rule for target.
zuazo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zuazo
.PHONY : zuazo

# fast build rule for target.
zuazo/fast:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/build
.PHONY : zuazo/fast

src/Timing/EventBase.o: src/Timing/EventBase.cpp.o

.PHONY : src/Timing/EventBase.o

# target to build an object file
src/Timing/EventBase.cpp.o:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/EventBase.cpp.o
.PHONY : src/Timing/EventBase.cpp.o

src/Timing/EventBase.i: src/Timing/EventBase.cpp.i

.PHONY : src/Timing/EventBase.i

# target to preprocess a source file
src/Timing/EventBase.cpp.i:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/EventBase.cpp.i
.PHONY : src/Timing/EventBase.cpp.i

src/Timing/EventBase.s: src/Timing/EventBase.cpp.s

.PHONY : src/Timing/EventBase.s

# target to generate assembly for a file
src/Timing/EventBase.cpp.s:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/EventBase.cpp.s
.PHONY : src/Timing/EventBase.cpp.s

src/Timing/PeriodicEvent.o: src/Timing/PeriodicEvent.cpp.o

.PHONY : src/Timing/PeriodicEvent.o

# target to build an object file
src/Timing/PeriodicEvent.cpp.o:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/PeriodicEvent.cpp.o
.PHONY : src/Timing/PeriodicEvent.cpp.o

src/Timing/PeriodicEvent.i: src/Timing/PeriodicEvent.cpp.i

.PHONY : src/Timing/PeriodicEvent.i

# target to preprocess a source file
src/Timing/PeriodicEvent.cpp.i:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/PeriodicEvent.cpp.i
.PHONY : src/Timing/PeriodicEvent.cpp.i

src/Timing/PeriodicEvent.s: src/Timing/PeriodicEvent.cpp.s

.PHONY : src/Timing/PeriodicEvent.s

# target to generate assembly for a file
src/Timing/PeriodicEvent.cpp.s:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/PeriodicEvent.cpp.s
.PHONY : src/Timing/PeriodicEvent.cpp.s

src/Timing/RegularEvent.o: src/Timing/RegularEvent.cpp.o

.PHONY : src/Timing/RegularEvent.o

# target to build an object file
src/Timing/RegularEvent.cpp.o:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/RegularEvent.cpp.o
.PHONY : src/Timing/RegularEvent.cpp.o

src/Timing/RegularEvent.i: src/Timing/RegularEvent.cpp.i

.PHONY : src/Timing/RegularEvent.i

# target to preprocess a source file
src/Timing/RegularEvent.cpp.i:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/RegularEvent.cpp.i
.PHONY : src/Timing/RegularEvent.cpp.i

src/Timing/RegularEvent.s: src/Timing/RegularEvent.cpp.s

.PHONY : src/Timing/RegularEvent.s

# target to generate assembly for a file
src/Timing/RegularEvent.cpp.s:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/RegularEvent.cpp.s
.PHONY : src/Timing/RegularEvent.cpp.s

src/Timing/Scheduler.o: src/Timing/Scheduler.cpp.o

.PHONY : src/Timing/Scheduler.o

# target to build an object file
src/Timing/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/Scheduler.cpp.o
.PHONY : src/Timing/Scheduler.cpp.o

src/Timing/Scheduler.i: src/Timing/Scheduler.cpp.i

.PHONY : src/Timing/Scheduler.i

# target to preprocess a source file
src/Timing/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/Scheduler.cpp.i
.PHONY : src/Timing/Scheduler.cpp.i

src/Timing/Scheduler.s: src/Timing/Scheduler.cpp.s

.PHONY : src/Timing/Scheduler.s

# target to generate assembly for a file
src/Timing/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/Timing/Scheduler.cpp.s
.PHONY : src/Timing/Scheduler.cpp.s

src/glad.o: src/glad.c.o

.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i

.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s

.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) -f CMakeFiles/zuazo.dir/build.make CMakeFiles/zuazo.dir/src/glad.c.s
.PHONY : src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... zuazo"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... src/Timing/EventBase.o"
	@echo "... src/Timing/EventBase.i"
	@echo "... src/Timing/EventBase.s"
	@echo "... src/Timing/PeriodicEvent.o"
	@echo "... src/Timing/PeriodicEvent.i"
	@echo "... src/Timing/PeriodicEvent.s"
	@echo "... src/Timing/RegularEvent.o"
	@echo "... src/Timing/RegularEvent.i"
	@echo "... src/Timing/RegularEvent.s"
	@echo "... src/Timing/Scheduler.o"
	@echo "... src/Timing/Scheduler.i"
	@echo "... src/Timing/Scheduler.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

